In [1]:
'''
Author: Dhruv B Kakadiya

'''

'\nAuthor: Dhruv B Kakadiya\n\n'

Linear Regression Model using PyTorch built-ins

In [2]:
# importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.tree import DecisionTreeClassifier, export_graphviz, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score
from subprocess import call

In [3]:
# Imports
import torch.nn as nn

In [4]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [6]:
import torch

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [7]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [8]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

[tensor([[102.,  43.,  37.],
         [ 73.,  67.,  43.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 91.,  88.,  64.]]), tensor([[ 22.,  37.],
         [ 56.,  70.],
         [119., 133.],
         [ 22.,  37.],
         [ 81., 101.]])]

In [9]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)


Parameter containing:
tensor([[-0.5469, -0.4711,  0.2228],
        [ 0.4157,  0.3714,  0.5208]], requires_grad=True)
Parameter containing:
tensor([-0.1389,  0.2595], requires_grad=True)


Optimizer

In [10]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [11]:
# Import nn.functional
import torch.nn.functional as F
# Define loss function
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(12549.9307, grad_fn=<MseLossBackward>)


In [12]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred, yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(inputs), targets))

In [13]:
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

Training loss:  tensor(13.0428, grad_fn=<MseLossBackward>)


In [14]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.0239,  71.5527],
        [ 83.3693,  99.5655],
        [114.8806, 133.5022],
        [ 26.0938,  43.7752],
        [100.9757, 113.3195],
        [ 58.0239,  71.5527],
        [ 83.3693,  99.5655],
        [114.8806, 133.5022],
        [ 26.0938,  43.7752],
        [100.9757, 113.3195],
        [ 58.0239,  71.5527],
        [ 83.3693,  99.5655],
        [114.8806, 133.5022],
        [ 26.0938,  43.7752],
        [100.9757, 113.3195]], grad_fn=<AddmmBackward>)

In [15]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])