PyTorch basics - Linear Regression from scratch

In [1]:
'''
Author: Dhruv B Kakadiya

'''

'\nAuthor: Dhruv B Kakadiya\n\n'

In [2]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [16]:
# importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.tree import DecisionTreeClassifier, export_graphviz, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score
from subprocess import call

In [17]:
import torch

In [18]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [19]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [20]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [21]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.7317, -1.2505,  0.3836],
        [ 0.9070,  0.0806,  0.5828]], requires_grad=True)
tensor([ 0.0287, -1.2243], requires_grad=True)


In [22]:
# Define the model
def model(x):
    return x @ w.t() + b
  
# Generate predictions
preds = model(inputs)
print(preds)
print(targets)

tensor([[-13.8492,  95.4441],
        [-18.8846, 125.7003],
        [-81.6368, 122.2839],
        [ 35.0809, 116.3151],
        [-42.6845, 109.8883]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Loss Function

In [23]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(8425.2305, grad_fn=<DivBackward0>)


In [24]:
# Compute gradients
loss.backward()

# Gradients for weights
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[ 0.7317, -1.2505,  0.3836],
        [ 0.9070,  0.0806,  0.5828]], requires_grad=True)
tensor([[ -8072.3750, -10755.6621,  -6149.3979],
        [  2126.8538,    995.6473,    870.0427]])
tensor([ 0.0287, -1.2243], requires_grad=True)
tensor([-100.5948,   21.9263])


In [25]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-13.8492,  95.4441],
        [-18.8846, 125.7003],
        [-81.6368, 122.2839],
        [ 35.0809, 116.3151],
        [-42.6845, 109.8883]], grad_fn=<AddBackward0>)


In [26]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(8425.2305, grad_fn=<DivBackward0>)


In [27]:
# Compute gradients
loss.backward()

# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

print(w)

tensor([[ 0.8931, -1.0354,  0.5066],
        [ 0.8644,  0.0607,  0.5654]], requires_grad=True)


In [28]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(4722.3564, grad_fn=<DivBackward0>)


In [29]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [30]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(612.4523, grad_fn=<DivBackward0>)


In [31]:
# Print predictions
preds

tensor([[ 66.2592,  76.0827],
        [ 90.7835, 103.3186],
        [ 84.5672, 117.6493],
        [ 74.1543,  71.6410],
        [ 85.8753, 103.2966]], grad_fn=<AddBackward0>)